### ISSUE TITLE
Problem in Exporting data

### ISSUE THREAD

**Issue by 23BCA309** [vtcbca/csv-file-program-23BCA309#2]
I partially understand this assignment. i have problem or confusion how i export my table data in to csv file.

if anybody knows, please help me to solve this problem.

**Comment by 23BCA305** [comment]
i have same problem. but try to use dump command to export data

**Comment by 23bca307** [comment]
not use dump command . to export table data you have o use below command.

1. first create table and insert record.
2. now apply below command one by one
.mode column
.mode csv
.output <path>.csv  [ replace path with filename ]

3. write selec * from <tablename>

**Comment by 23BCA309** [comment]
![export data](https://github.com/user-attachments/assets/edbdea21-d538-4e64-9e3b-093f713c9875)
thank you...you solve my problem
